# Collector specific configuration

plans_url: "https://api.hpc.tools/v2/public/plan"

api_pattern: "https://api.hpc.tools/v2/public/project/search?planCodes={code}&excludeFields=governingEntities,targets&limit={rows}"

hrp_subtitles:
  - "besoins humanitaires et plan de réponse"
  - "humanitarian needs and response plan"
  - "humanitarian response plan"
  - "necesidades humanitarias y plan de respuesta"
  - "original humanitarian needs and response plan"
  - "plan de respuesta humanitaria"

tags:
  - "humanitarian response plan-hrp"
  - "who is doing what and where-3w-4w-5w"

headers:
  - "name"
  - "versionCode"
  - "currentRequestedFunds"
  - "objective"
  - "partners"
  - "startDate"
  - "endDate"
  - "globalClusters"
  - "locations"
  - "organizations"
  - "plans"
  - "Response plan code"

hrp_gho_exceptions:
  HRP_2025:
    add:
      - "ETH"
      - "SYR"
  HRP_20206:
    add:
      - "SYR"
